# Summary Assignment 1
<blockquote>This assignment will be autograded. To avoid autograder errors, please do not add or delete any cells. Also, run all cells even if they are hidden and not requiring any input from you.</blockquote>

In [ ]:
# Load Necesary Libraries for Autograding
library(testthat)

# Problem 1

Let the joint PDF $f(X,Y)$ be represented by the following table of values:


|  | y=-1| y=0 | y=1 | y=2 |
| :--- | :----: | :---: | :---: | ---: |
| $x=2$ | 0.1 | 0 | 0.15 | 0 |
| $x=3$ | 0.1 | 0.1 | 0.05 | 0.05 |
| $x=4$ | 0 | 0.05 | 0.15 | 0.25 |

 **Part A)** Find $E[X]$ and $E[Y]$. Save your answers as `p1.a.ex` and `p1.a.ey`.

In [ ]:
x_vals <- c(2, 3, 4)
y_vals <- c(-1, 0, 1, 2)

fxy <- matrix(
  c(0.10, 0.00, 0.15, 0.00,
    0.10, 0.10, 0.05, 0.05,
    0.00, 0.05, 0.15, 0.25),
  nrow = length(x_vals),
  byrow = TRUE
)

sum_f <- sum(fxy)
sum_f

# 4) Compute marginals P_X(x) and P_Y(y)
px <- rowSums(fxy)   # sums across y for each fixed x
py <- colSums(fxy)   # sums across x for each fixed y
px
py

# 5) Compute expectations using marginals
p1.a.ex <- sum(x_vals * px)        # E[X] = sum_x x * P_X(x)
p1.a.ey <- sum(y_vals * py)        # E[Y] = sum_y y * P_Y(y)

p1.a.ex
p1.a.ey

#p1.a.ex <- 3.2
#p1.a.ey <- 0.75


[,1] [,2] [,3] [,4]
[1,] 0.1  0.00 0.15 0.00
[2,] 0.1  0.10 0.05 0.05
[3,] 0.0  0.05 0.15 0.25

[1] 1

[1] 0.25 0.30 0.45

[1] 0.20 0.15 0.35 0.30

[1] 3.2

[1] 0.75

In [ ]:
# Hidden Test Cell
# NOTE: This cell contains hidden tests. You will not see if you passed these tests until you submit your assignment.
# Any cell labeled "Hidden Test Cell" MAY have hidden tests.

**Part B)** Find $E[XY]$. Save your answer as `p1.b.exy`.

In [6]:
## Part B — Expectation of XY

# Reuse x_vals, y_vals, and fxy from Part A

# 1) Create all (x, y) combinations with their joint probabilities
#    Use outer() to multiply x * y for each (x, y) pair
xy_products <- outer(x_vals, y_vals, FUN = "*")
xy_products


# 2) Multiply elementwise by the joint probabilities f(x,y)
xy_weighted <- xy_products * fxy
xy_weighted

# 3) Sum over all entries to get E[XY]
p1.b.exy <- sum(xy_weighted)
p1.b.exy
# [1] 2.8


#p1.b.exy <- 2.85


[,1] [,2] [,3] [,4]
[1,] -2   0    2    4   
[2,] -3   0    3    6   
[3,] -4   0    4    8

[,1] [,2] [,3] [,4]
[1,] -0.2 0    0.30 0.0 
[2,] -0.3 0    0.15 0.3 
[3,]  0.0 0    0.60 2.0

[1] 2.85

In [ ]:
# Hidden Test Cell

**Part C)** Are $X$ and $Y$ independent? Answer the boolean value `TRUE` if they are independent and `FALSE` if they are not independent. Save your answer as `p1.c`.

In [ ]:
p1.c <- FALSE


In [ ]:
# Hidden Test Cell
if(!test_that("Check that answer is correct type", expect_is(p1.c, "logical"))){
    print("Make sure your answer is a boolean!")
}


**Part D)** Define $U=X+Y$. What is $P(U \ge 4)$? Save your answer as `p1.d`.

In [ ]:
p1.d <- 0.55


In [ ]:
# Hidden Test Cell

# Problem 2

You work at the front desk of a library, and have to manage the printer. Sadly, the printer is old, and regularly jams. You know that your boss will only replace the printer if there is hard evidence, so you decide to record the number of times the printer was able to print successfully **before** it jammed. These values are recorded in `prints` below. Assume that these values are independent and identically distributed.

In [ ]:
prints = c(12, 9, 3, 17, 5, 5, 3, 7, 0, 5, 17, 6, 9, 1, 13)

**Part A)** Let $X$ be a random variable for the number of times the printer was able to print before it jammed. Then $X$ follows a Geometric distribution with some unknown probability $p$, where $X_i \in {0, 1, 2, \dots}$. We want to estimate $p$, that is the probability that the printer fails. Using the method of moments, what is the estimate $\hat{p}$?

1. $\dfrac{1}{\bar{X}}$
2. $\dfrac{1}{\bar{X}+1}$
3. $\dfrac{\bar{X}}{\bar{X}+1}$
4. $\dfrac{\bar{X}}{1-\bar{X}}$
5. None of the above.

Save the NUMBER corresponding to the correct answer into the variable `p2.a`.

In [ ]:
p2.a <- 2


In [ ]:
# Hidden Test Cell
if(!test_that("Make sure your answer is the NUMBER of the correct answer", expect_is(p2.a, "numeric"))){
    print("Make sure your answer is the number corresponding to your answer.")
}


**Part B)** Given your solution to **Part A**, calculate the estimated probability for the recorded data. Save this value into `p2.b`. (Include at least 2 decimal places.)

In [ ]:
p2.b <- 1 / (mean(prints) + 1)


In [ ]:
# Hidden Test Cell

**Part C)** Let's try to visualize how well our estimator actually fits the data. 

To create a histogram of the "prints" data, one only needs to type <code>hist(prints)</code>. In order to store the results in a way the autograder can interpret, we need to store this in a variable like this: <code>my_hist_var=hist(prints)</code>

Recall that the y-axis of a histogram can be scaled in many different ways.
In order to make it so that the total area of each bar is the proportion of observations observed in the corresponding bin, we need to add "prob=T" (probability equals true) to the histogram command. This is called a "density histogram".

Finally, to control the way the bins break on the x-axis, we need to give a sequence of break values. As an example unrelated to this exercise, we might type <code>my_hist_var = hist(mydata,prob=T,breaks=seq(1,8,1))</code> to put breaks at 1,2, ..., 8.

For this exercise,  create a density histogram of the `prints` values and store it in variable `p2.c.hist`. Center the bars on the integers 0 through 17 by making breaks at -0.5, 0.5, 1.5, ..., 17.5. Add the curve of a geometric distribution, with the probability of what you estimated in **Part B**, ontop of your histogram. Think about how well this curve approximates the distribution.

In [ ]:
p2.c.hist <- hist(prints, prob=TRUE, breaks=seq(0, max(prints)+1, 1))

# Optional overlay of fitted geometric PMF (failures-before-first-success)
k <- 0:max(prints)
points(k, dgeom(k, prob=p2.b))


In [ ]:
# Hidden Test Cell

**Part D)** what is the *true* underlying probability of this distribution? Save your answer as `p2.d` and round your answer to two decimal places. If it's not possible to answer this question, save your answer as the string `"not possible"`.

In [ ]:
p2.d <- "not possible"


In [ ]:
# Hidden Test Cell